GET http://localhost:3000/

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username":"Solar",
    "password":"youngsun",
    "name":"SOLAR",
    "email": "solar1354@gmail.com"
}


